apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
          args:
            - --alpha-config=/config/alpha-config.yaml # use alpha-config to set access-token in `Authorization: Bearer <jwt>` header (see: https://github.com/oauth2-proxy/oauth2-proxy/issues/843#issuecomment-824244308)
            - --cookie-secure=true
            - --cookie-samesite=lax
            - --cookie-refresh=1h
            - --cookie-expire=4h
            - --cookie-name=_oauth2_proxy_istio_ingressgateway
            - --whitelist-domain=petclinic.ikarpov.net,dev-jf-ctr97.us.auth0.com # auth0 domain is needed for logout redirect
            - --email-domain=*
            - --silence-ping-logging=true
            - --skip-provider-button=true
          env:
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: OAUTH2_PROXY_COOKIE_SECRET
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
          ports:
            - containerPort: 4180
              protocol: TCP
          readinessProbe:
            periodSeconds: 3
            httpGet:
              path: /ping
              port: 4180
          volumeMounts:
            - name: config
              mountPath: /config/alpha-config.yaml
              subPath: alpha-config.yaml
              readOnly: true
            - name: secret
              mountPath: /config/oauth-client.secret
              subPath: oauth-client.secret
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: oauth2-proxy
        - name: secret
          secret:
            secretName: oauth2-proxy
            items:
              - key: OAUTH2_PROXY_CLIENT_SECRET
                path: oauth-client.secret
