apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:HDd0wsY4WGyW1TH3hcxdHQlj+7tW7o5m87mUPUWO6UdBoaHXEfjuBzb40tynyoS0bHf/f2nrDv8+ZnSaRlsMfDVIWYoPZWjLfuxnD98aQuZCwjX5VKx6uZgRp+XO/T9OQQLis5DIE8Zbyehqc2aA208AfzOkhG9ZWs4h5iEkiSTs7t8iVXJansW42dBkOEqX8bD0oONm8m2YQLmoR0fksqCAnKsP8VqyrX3TgxbrbvfrXycRkH5gfgtFf0yIgXWoZyrOJ6BEwyvDLDKzT316z35Qy++Y0br8tHxyATdhPVGXSqfARVd3o3rF8TyzZGqlF38ouxsH4odawNYqHfIo0w8dKIvIolH1Oo+VTUprBiQSinxIyB8QoU6kwYyR0LZvPRz1BN3PIJbtd0F5ynK79S0RRA3IhirDPeVwqMKxZXejA/KB,iv:2ygCGQdg0Q9q0I3nH/aVuo4fNVvx4tFHOnNaiGXAWaE=,tag:YWLQDSxwKthcm8GHw0Aqjg==,type:str]
kind: Secret
metadata:
    name: regcred
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-25T17:14:03Z"
    mac: ENC[AES256_GCM,data:LUgLzYTRZudXtiixRbk04GrDCUVt8t/MQuq9Y1NaQu1reyhH8DHM4CBOhfquEVzPINX17mAaGsuIXe74dz8tlvXpFjSpn6mneozv5ZslR9LkfCUAzGztW10GwKJhZoa7mSXtlLupXHyElgesE2V32L7pDZCZdzok2mofMD/QFfk=,iv:MzyW7Onf+91fDOF2WFT3GSQWr3yK4uoBV6084xs6bpU=,tag:CrW55TVK3e7F4xSFk+tzKA==,type:str]
    pgp:
        - created_at: "2022-07-25T17:13:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DSneaBMDks5MSAQdA+E4H+K/3wbnwEYfzQqyBasPYiHGXUkaWuoDI96XNtDIw
            R+ev0tZcKw6wWLppVjBBFuFq2SaPtupnYVDXduJPO53xi9SzY+t2pS7uuooWVVdS
            0l4BDUPtKTwppxkAtL5m4b5PshLROxkBSOrY0pa1yjC9xlv9n68TOwWWf6Ker0+i
            F3798G8c+rgar4hURo/of7UIJg+T8V2J8KpxGKTso+2S5VPqcfgwZnbB8McWWbGk
            =+Ft9
            -----END PGP MESSAGE-----
          fp: 07E81402040ACE290C5A75216D8FBECA4E3C4965
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
