apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: petclinic
spec:
  secretName: petclinic-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - petclinic.ikarpov.net